### PR TITLE
Stricter schema, take 1

### PR DESCRIPTION
**Pull request by yaronf**
Improve the JSON schema, per our ongoing discussion.

### CODE REVIEW

**Review by thomas-fossati — COMMENTED** [review]
Looks good.  I have transplanted all of these in the CDDL.

It seems to me that keeping the two alive and in sync is a PITA though.  I'd rather drop JSON-schema in favour of the new kid on the block.

**Comment by yaronf** [comment]
> Looks good. I have transplanted all of these in the CDDL.
> 
> It seems to me that keeping the two alive and in sync is a PITA though. I'd rather drop JSON-schema in favour of the new kid on the block.

I don't think CDDL is being used by anybody outside the IETF. Let's try to keep both for now. I will manually review them one more time before we publish -05.

**Comment by thomas-fossati** [comment]
> > Looks good. I have transplanted all of these in the CDDL.
> > It seems to me that keeping the two alive and in sync is a PITA though. I'd rather drop JSON-schema in favour of the new kid on the block.
> 
> I don't think CDDL is being used by anybody outside the IETF. Let's try to keep both for now. I will manually review them one more time before we publish -05.

If you are keen on doing the work, this surely works for me.  I suggest we add a good bunch of tests to safeguard consistency though, using the scaffolding I added in #132.  (It still needs some cleanup.)

> I'm just a bit worried that if we modify the JSON Schema file in _both_ pull requests, it's going to end in tears.

I could transplant manually in #132 if you want, there is not a lot after all.  Or we can merge this and I rebase the other.

**Comment by yaronf** [comment]
> > I'm just a bit worried that if we modify the JSON Schema file in _both_ pull requests, it's going to end in tears.
> 
> I could transplant manually into #132 if you want, there is not a lot after all. Or we can merge this and I rebase the other.
Yes, please transplant manually (you may have already done it), and I will drop the other PR.

**Comment by thomas-fossati** [comment]
> Yes, please transplant manually (you may have already done it), and I will drop the other PR.

ok, done in dcb53c1

**Comment by thomas-fossati** [comment]
this is now subsumed under #132

**Pull request closed without merging**
