### PR TITLE
Fix obsolete wording

### LINKED ISSUE #319: obsolete wording (assumes 1.2 is the latest and greatest)
_"In fact, the cipher suites recommended by this document for TLS 1.2 (Section 4.2 below) are only available in this version."_

* Why are they not in TLS 1.3 ? :P Or are they?

_"TLS 1.1 and 1.2 never negotiate 40-bit or 56-bit export ciphers."_

* This (misleadingly) suggests TLS 1.3 might however do this?

### PR DESCRIPTION
**Pull request by yaronf**
Fixes #319

### CODE REVIEW

**Review by stpeter — APPROVED** [review]

**Comment by thomas-fossati** [comment]
A general comment: it feels like in the light of RFC 8996 we shouldn't even provide a rationale for not using 1.0 and 1.1.  Maybe this whole block of text could be condensed into a single reference to 8996?

**Comment by stpeter** [comment]
> A general comment: it feels like in the light of RFC 8996 we shouldn't even provide a rationale for not using 1.0 and 1.1. Maybe this whole block of text could be condensed into a single reference to 8996?

There are two schools of thought here: (1) it can't hurt to remind people that 1.0 and 1.1 are bad (2) just read 8996. I think I lean toward (2).

**Comment by yaronf** [comment]
> There are two schools of thought here: (1) it can't hurt to remind people that 1.0 and 1.1 are bad (2) just read 8996. I think I lean toward (2).

I guess I lean more towards (1), because this is an extensive document about TLS and we cannot punt on something so important as saying 1.0 and 1.1 are bad.

**Review by thomas-fossati — APPROVED** [review]

**Comment by stpeter** [comment]
> > There are two schools of thought here: (1) it can't hurt to remind people that 1.0 and 1.1 are bad (2) just read 8996. I think I lean toward (2).
> 
> I guess I lean more towards (1), because this is an extensive document about TLS and we cannot punt on something so important as saying 1.0 and 1.1 are bad.

Sure, that works for me! My preferences are not strong on this, and what you say makes sense.

**Pull request merged**
